language: java
jdk:
  - openjdk8
before_install:
  - chmod +x mvnw
  - export TZ=Brazil/East
deploy:
  provider: heroku
  api_key:
    - secure: $TOKEN_HEROKU
  app: $APP
install: true
script: mvn clean package -DskipTests=true

